# Generated by Django 3.1.7 on 2021-02-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapper',
            old_name='end_req_time',
            new_name='exec_end',
        ),
        migrations.RenameField(
            model_name='mapper',
            old_name='start_req_time',
            new_name='exec_start',
        ),
    ]
