# Generated by Django 3.1.7 on 2021-03-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20210228_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapperModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REQUEST_ID', models.CharField(max_length=128, unique=True)),
                ('exec_start', models.DateTimeField(null=True)),
                ('exec_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mapper',
        ),
    ]
